---
title: "DS190 Outline"
author: "Wendy Zhang"
date: today
format:
  pdf:
    number-sections: true
    number-depth: 5
---

*Questions:*
a.	Would it be okay if the bulk of writing is the introduction and methods? At this point, I am in the process of replicating Germani et al. (2025) and running their scrips (and trying to debug), so I’m not sure if the current plan is too ambitious. 
b.	For the discussion, is it okay to include more subjective reflections on the process of learning? Or should it be solely technical (4.a)

## Introduction

### Review of the problem for multiverse
### MRI preprocessing and analysis steps overview

## Methods

### Dataset
Human Connectome Project
### Procedure
Detailed explanation of Germani et al. (2025), which is an attempt of multiverse analysis 
#### 12 pipelines for 2 softwares (FSL, SPM) on the motor task
### Current project
#### Replicating Germani et al. (2025)
#### 12 pipelines for 1 software (FSL) on the gambling task

## Results
### Replicating Germani et al. (2025)
#### Issues with repository on github
##### Data structure
##### Errors in script
#### Efficiency

### Running the scripf on the gambling task
#### New findings

## Discussion
### Reflection on current project
#### What the current project has achieved
#### Data science ethics
#### Multiverse analysis’ issue
###	Next steps of the project
####	12 pipelines for both FSL and SPL on gambling task
####	Optimizing the script for easier accessibility

