---
title: "DS190 Topic"
author: "Wendy Zhang"
date: today
date-format: "MMMM D, YYYY"
format:
  pdf:
    number-sections: true
bibliography: topic.bib
---

My capstone project topic is: Effect of Variations in the Analaysis Pipeline on Self-Regulation Related fMRI Correlates. I took a fMRI class and am very interested in investigating preprocessing and data analysis with fMRI for my project. In fMRI analysis, there are multiple steps of raw data preprocessing prior to starting analysis, and the order of preprocessing varies across labs, with different packages (e.g., Nipype, SPM) and different parameters (e.g., Harvard brain atlas, individual parcellation) adopted based on labs' individual preferences (i.e., what they were used to). Recently, there are labs that focus on how these changes would affect the results of fMRI studies. The prior paper of such related projects is @botvinik-nezer2020variability, where they sent the same dataset and research questions to 70 different groups, and found an almost even split on whether the hypotheses were supported across groups due to their different analysis pipelines. I am interested in exploring this topic further by using a dataset collected by Dr. Zeynep Enkavi that consisted of self-regulation tasks.

## References
